backend:
  name: github
  branch: master # change this to your branch
  repo: zzXavier/acm-test # change this to your repo
  site_domain: 051105.cn # change this to your domain
  base_url: https://051105.cn # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration